---
- name: Set the system files with the correct flag to enable or disable the spectre and meltdown protection
  hosts: all
  become: true
  gather_facts: false
  vars:
    # The path to the x86 specific kernel flags.
    sys_kernel_debug_path: "/sys/kernel/debug/x86"
    # Indirect Branch Restricted Speculation (ibrs)
    ibrs_path: "{{ sys_kernel_debug_path }}/ibrs_enabled"
    # Page Table Isolation (pti)
    pti_path: "{{ sys_kernel_debug_path }}/pti_enabled"
    # Retpoline (retp)
    retp_path: "{{ sys_kernel_debug_path }}/retp_enabled"
  vars_prompt:
    - name: "retp_value"
      prompt: "Retpoline (retp) enabled? "
      default: "1"
      private: no
    - name: "ibrs_value"
      prompt: "Indirect Branch Restricted Speculation (ibrs) enabled? "
      default: "1"
      private: no
    - name: "pti_value"
      prompt: "Page Table Isolation (pti) enabled? "
      default: "1"
      private: no
  tasks:
    # Set the retp_enabled value based on the string variable.
    - name: Setting retp value
      shell: "echo {{ retp_value }} > {{ retp_path }}"

    # Set the ibrs_enabled value based on the string variable.
    - name: Setting ibrs value
      shell: "echo {{ ibrs_value }} > {{ ibrs_path }}"

    # Do not set ibpb flag. ibpb is now read-only and managed by the kernel.

    # Set the pti_enabled value based on the string variable.
    - name: Setting pti value
      shell: "echo {{ pti_value }} > {{ pti_path }}"
